name: Buld an apk and push it

on:
  push:
    branches:
      - main
      - test-github-actions

jobs:
  build:
    defaults:
      run:
        working-directory: PyroApp
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install npm dependencies
      run: |
        npm install
    - name: Build Android Release
      run: |
        cd android && ./gradlew assembleDebug
    - name: List files
      run: |
        ls -R android/
    - name: Create dir if not exists
      run: |
        mkdir -p android/app/build/outputs/apk/
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: app-debug.apk
        path: android/app/build/outputs/apk/
        retention-days: 30
